/*
 * Copyright (C) 2009-2014 SAP SE or an SAP affiliate company. All rights reserved
 */
jQuery.sap.declare("i2d.pp.mrpcockpit.reuse.util.CalculationEngine");jQuery.sap.require("sap.ca.ui.message.message");jQuery.sap.require("i2d.pp.mrpcockpit.reuse.util.CommonConstants");
i2d.pp.mrpcockpit.reuse.util.CalculationEngine=function(m){this.Constants=i2d.pp.mrpcockpit.reuse.util.CommonConstants;this.oModelI18N=m};
i2d.pp.mrpcockpit.reuse.util.CalculationEngine.prototype.previewTable=function(m,c,s,S,d){this._dShortageStartDate=s;this._dShortageEndDate=S;this._aSupDemItems=[];if(!c){return[-1,this._aSupDemItems]}if(!this.isInputDataValid(d,c.ChangedAvailabilityDate)){return[-2,this._aSupDemItems]}this._aSupDemItems=m;this.initSupDemItems();var o=this.getActiveSupplyDemandItem(c);if(!o&&c.MaterialShortageSolutionType!==this.Constants.SOLUTIONTYPE_ACCEPT){o=this.createActiveSupplyDemandItem(c)}var C=this.getSupDemItemCategory(o,c);switch(C){case this.Constants.CARD_CATEGORY_INCREASE:this.runPreviewTypeIncrease(c,o);break;case this.Constants.CARD_CATEGORY_RESCHEDULE:this.runPreviewTypeReschedule(c,o);break;case this.Constants.CARD_CATEGORY_CHANGE:this.runPreviewTypeChange(c,o);break;case this.Constants.CARD_CATEGORY_ACCEPT:break}return[0,this._aSupDemItems]};
i2d.pp.mrpcockpit.reuse.util.CalculationEngine.prototype.isInputDataValid=function(t,T){var d=new Date(t.getUTCFullYear(),t.getUTCMonth(),t.getUTCDate());var a=new Date(T.getUTCFullYear(),T.getUTCMonth(),T.getUTCDate());var v=true;if(a.getTime()<d.getTime()){v=false}else if(this._dShortageStartDate&&this._dShortageEndDate){if(!(this._dShortageStartDate instanceof Date)||!(this._dShortageEndDate instanceof Date)){v=false}else if(this._dShortageStartDate>this._dShortageEndDate){v=false}}return v};
i2d.pp.mrpcockpit.reuse.util.CalculationEngine.prototype.initSupDemItems=function(){for(var i=0;i<this._aSupDemItems.length;i++){var o=this._aSupDemItems[i];o.MRPElementOpenQuantity=parseFloat(o.MRPElementOpenQuantity);o.MRPAvailableQuantity=parseFloat(o.MRPAvailableQuantity);o.ChangedMrpElement=false;if(o.MRPAvailableQuantity<o.MaterialShortageCriticalQty){o.InitialShortage=true}}};
i2d.pp.mrpcockpit.reuse.util.CalculationEngine.prototype.getSupDemItemCategory=function(s,c){var C="";switch(c.MaterialShortageSolutionType){case this.Constants.SOLUTIONTYPE_ACCEPT:C=this.Constants.CARD_CATEGORY_ACCEPT;break;case this.Constants.SOLUTIONTYPE_PO_CREATE:case this.Constants.SOLUTIONTYPE_TO_CREATE:C=this.Constants.CARD_CATEGORY_RESCHEDULE;break;default:var S=s.MRPElementAvailyOrRqmtDate;var d=c.ChangedAvailabilityDate;var i=s.MRPElementOpenQuantity;var a=parseFloat(c.MRPElementChangeOpenQuantity);if(d&&S){if(S.getTime()===d.getTime()&&i!==a){C=this.Constants.CARD_CATEGORY_INCREASE}if(S.getTime()!==d.getTime()&&i===a){C=this.Constants.CARD_CATEGORY_RESCHEDULE}if(S.getTime()!==d.getTime()&&i!==a){C=this.Constants.CARD_CATEGORY_CHANGE}}break}return C};
i2d.pp.mrpcockpit.reuse.util.CalculationEngine.prototype.getActiveSupplyDemandItem=function(c){var s=null;switch(c.MaterialShortageSolutionType){case this.Constants.SOLUTIONTYPE_PO_CREATE:case this.Constants.SOLUTIONTYPE_TO_CREATE:break;default:for(var i=0;i<this._aSupDemItems.length;i++){var o=this._aSupDemItems[i];if(o.MRPElement===c.MRPElementExternalID&&o.MRPElementCategory===c.MRPElementCategory&&o.MRPElementItem===c.MRPElementItemExternalID&&o.MRPElementScheduleLine===c.MRPElementScheduleLineExtID){s=o}}break}return s};
i2d.pp.mrpcockpit.reuse.util.CalculationEngine.prototype.createActiveSupplyDemandItem=function(c){var d=new Date("3333","03","03");c.MRPElementExternalID="";if(this.oModelI18N){var b=this.oModelI18N.getResourceBundle();c.MRPElementExternalID="["+b.getText("NEW")+"]"}var s=new Object();s.Index=this._aSupDemItems.length+1;s.MRPElement=c.MRPElementExternalID;s.MRPElementAvailyOrRqmtDate=d;s.MRPElementOpenQuantity=parseFloat(c.MRPElementChangeOpenQuantity);s.UnitOfMeasureTechnicalName=c.UnitOfMeasureTechnicalName;s.MaterialID=c.MaterialID;s.ChangedMrpElement=true;s.MRPElementCategoryShortName=c.MRPElementCategoryShortName;switch(c.MaterialShortageSolutionType){case this.Constants.SOLUTIONTYPE_PO_CREATE:s.Vendor=c.Vendor;s.VendorName=c.VendorName;s.MRPElementCategory=this.Constants.MRP_ELEMENT_CATEGORY_POITEM;s.MRPElementBusinessPartnerType=this.Constants.MRP_ELEMENT_BUSINESSPARTNERTYPE_SUPPLIER;s.MRPElementBusinessPartnerID=c.Vendor;s.MRPElementBusinessPartnerName=c.VendorName;break;case this.Constants.SOLUTIONTYPE_TO_CREATE:s.MRPElementCategory=this.Constants.MRP_ELEMENT_CATEGORY_RELORD;s.MRPElementBusinessPartnerType=this.Constants.MRP_ELEMENT_BUSINESSPARTNERTYPE_ISSUINGLOC;s.MRPElementBusinessPartnerID=c.SupplyingPlant;s.MRPElementBusinessPartnerName=c.VendorName;break}this._aSupDemItems.push(s);return s};
i2d.pp.mrpcockpit.reuse.util.CalculationEngine.prototype.setActiveSupDemItem=function(c,s){s.MRPElementAvailyOrRqmtDate=c.ChangedAvailabilityDate;s.MRPElementOpenQuantity=parseFloat(c.MRPElementChangeOpenQuantity);s.ChangedMrpElement=true};
i2d.pp.mrpcockpit.reuse.util.CalculationEngine.prototype.runPreviewTypeIncrease=function(c,s){var d=0;var S=s.MRPElementAvailyOrRqmtDate;var a=s.MRPElementOpenQuantity;var b=parseFloat(c.MRPElementChangeOpenQuantity);this.setActiveSupDemItem(c,s);this.adaptAvailableQuantities();d=b-a;for(var i=0;i<this._aSupDemItems.length;i++){var o=this._aSupDemItems[i];o.Index=i+1;if(!this.isItemStockLine(o)){if(!this.isShortageIntervalDefined()||this.isItemInShortageInterval(o)){if(o.MRPElementAvailyOrRqmtDate>=S){o.MRPAvailableQuantity+=d}}}}};
i2d.pp.mrpcockpit.reuse.util.CalculationEngine.prototype.findSourcePosition=function(s){var p=0;for(var i=0;i<this._aSupDemItems.length;i++){var o=this._aSupDemItems[i];if(o.MRPElement===s.MRPElement&&o.MRPElementCategory===s.MRPElementCategory&&o.MRPElementItem===s.MRPElementItem&&o.MRPElementScheduleLine===s.MRPElementScheduleLine){p=i;break}}return p};
i2d.pp.mrpcockpit.reuse.util.CalculationEngine.prototype.findTargetPosition=function(c,s){var S=c.ChangedAvailabilityDate;var t=this._aSupDemItems.length;for(var i=0;i<this._aSupDemItems.length;i++){var o=this._aSupDemItems[i];if(!this.isItemStockLine(o)){if(S.getTime()<o.MRPElementAvailyOrRqmtDate.getTime()){t=i;break}else if(o.MRPElementAvailyOrRqmtDate.getTime()===S.getTime()){if(o.MRPElementOpenQuantity<0){t=i;break}else if(o.MRPElementCategoryShortName>s.MRPElementCategoryShortName){t=i;break}else if(o.MRPElementCategoryShortName===s.MRPElementCategoryShortName){if(o.MRPElement>s.MRPElement){t=i;break}}}}}return t};
i2d.pp.mrpcockpit.reuse.util.CalculationEngine.prototype.isItemStockLine=function(o){if(o.MRPElementCategory===this.Constants.MRP_ELEMENT_CATEGORY_STOCK){return true}else{return false}};
i2d.pp.mrpcockpit.reuse.util.CalculationEngine.prototype.isItemSupply=function(o){if(o.MRPElementOpenQuantity<0){return false}else{return true}};
i2d.pp.mrpcockpit.reuse.util.CalculationEngine.prototype.isItemInShortageInterval=function(o){var d=o.MRPElementAvailyOrRqmtDate;if((this._dShortageStartDate<=d)&&(d<=this._dShortageEndDate)){return true}else{return false}};
i2d.pp.mrpcockpit.reuse.util.CalculationEngine.prototype.isShortageIntervalDefined=function(){if(this._dShortageStartDate===null||this._dShortageEndDate===null){return false}else{return true}};
i2d.pp.mrpcockpit.reuse.util.CalculationEngine.prototype.isItemStockLine=function(o){if(o.MRPElementCategory===this.Constants.MRP_ELEMENT_CATEGORY_STOCK){return true}else{return false}};
i2d.pp.mrpcockpit.reuse.util.CalculationEngine.prototype.setActiveSupDemItemQuantity=function(c,s,t){var S=c.ChangedAvailabilityDate;var q=c.MRPElementChangeOpenQuantity;var Q="";if(this._aSupDemItems.length===1){Q=0}else if((t>0)&&t===this._aSupDemItems.length-1){Q=this._aSupDemItems[t-1].MRPAvailableQuantity}else if((t>0)&&this._aSupDemItems[t-1].MRPElementAvailyOrRqmtDate.getTime()===S.getTime()&&!this.isItemStockLine(this._aSupDemItems[t-1])){Q=this._aSupDemItems[t-1].MRPAvailableQuantity}else if(this._aSupDemItems[t+1].MRPElementAvailyOrRqmtDate.getTime()===S.getTime()){if(this.isItemSupply(this._aSupDemItems[t+1])===true){Q=this._aSupDemItems[t+1].MRPAvailableQuantity}else if(t===0){Q=this._aSupDemItems[t+1].MRPAvailableQuantity-this._aSupDemItems[t+1].MRPElementOpenQuantity}else{Q=this._aSupDemItems[t-1].MRPAvailableQuantity}}else if(this._aSupDemItems[t+1].MRPElementAvailyOrRqmtDate.getTime()!==S.getTime()&&t===0){Q=this._aSupDemItems[t+1].MRPAvailableQuantity-q}else if(this._aSupDemItems[t+1].MRPElementAvailyOrRqmtDate.getTime()!==S.getTime()&&(t>0)){Q=this._aSupDemItems[t-1].MRPAvailableQuantity}this._aSupDemItems[t].MRPAvailableQuantity=Q};
i2d.pp.mrpcockpit.reuse.util.CalculationEngine.prototype.adaptAvailableQuantities=function(){var I=null;if(this._dShortageStartDate===null||this._dShortageEndDate===null){return}for(var i=0;i<this._aSupDemItems.length;i++){I=this._aSupDemItems[i];if(!this.isItemInShortageInterval(I)){I.MRPAvailableQuantity=""}}};
i2d.pp.mrpcockpit.reuse.util.CalculationEngine.prototype.runPreviewTypeReschedule=function(c,s){var S=s.MRPElementAvailyOrRqmtDate;var d=c.ChangedAvailabilityDate;var a=parseFloat(c.MRPElementChangeOpenQuantity);var b=parseFloat(c.MRPElementOpenQuantity);this.setActiveSupDemItem(c,s);var p=this.findSourcePosition(s);var I=this._aSupDemItems.splice(p,1);var P=this.findTargetPosition(c,s);this._aSupDemItems.splice(P,0,I[0]);this.setActiveSupDemItemQuantity(c,s,P);this.adaptAvailableQuantities();if(d<S){for(var i=0;i<this._aSupDemItems.length;i++){var o=this._aSupDemItems[i];o.Index=i+1;if(!this.isItemStockLine(o)){if(!this.isShortageIntervalDefined()||this.isItemInShortageInterval(o)){if(((o.MRPElementAvailyOrRqmtDate>=d))&&((o.MRPElementAvailyOrRqmtDate<S))){o.MRPAvailableQuantity+=a}}}}}else{for(var i=0;i<this._aSupDemItems.length;i++){var o=this._aSupDemItems[i];o.Index=i+1;if(!this.isItemStockLine(o)){if(!this.isShortageIntervalDefined()||this.isItemInShortageInterval(o)){if(((o.MRPElementAvailyOrRqmtDate>=S))&&((o.MRPElementAvailyOrRqmtDate<d))){o.MRPAvailableQuantity-=b}}}}}};
i2d.pp.mrpcockpit.reuse.util.CalculationEngine.prototype.runPreviewTypeChange=function(c,s){var d=0;var S=s.MRPElementAvailyOrRqmtDate;var a=c.ChangedAvailabilityDate;var b=s.MRPElementOpenQuantity;var e=parseFloat(c.MRPElementChangeOpenQuantity);this.runPreviewTypeReschedule(c,s);d=e-b;if(S<a){for(var i=0;i<this._aSupDemItems.length;i++){var o=this._aSupDemItems[i];o.Index=i+1;if(!this.isItemStockLine(o)){if(!this.isShortageIntervalDefined()||this.isItemInShortageInterval(o)){if(o.MRPElementAvailyOrRqmtDate>=a){o.MRPAvailableQuantity+=d}}}}}else{for(var i=0;i<this._aSupDemItems.length;i++){var o=this._aSupDemItems[i];o.Index=i+1;if(!this.isItemStockLine(o)){if(!this.isShortageIntervalDefined()||this.isItemInShortageInterval(o)){if(o.MRPElementAvailyOrRqmtDate>=S){o.MRPAvailableQuantity+=d}}}}}};
i2d.pp.mrpcockpit.reuse.util.CalculationEngine.prototype.getSDItemsForShortage=function(s,m){var S={};var a=[];for(var k in m){if(m.hasOwnProperty(k)){if(k.substr(0,17)=="SupplyDemandItems"){S=m[k];if((S.MRPPlant===s.MRPPlant)&&(S.MaterialID===s.MaterialID)&&(S.MRPArea===s.MRPArea)&&(S.MRPPlant===s.MRPPlant)&&(S.MRPPlanningSegmentType===s.MRPPlanningSegmentType)&&(S.MRPPlanningSegmentNumber===s.MRPPlanningSegmentNumber)){a.push(S)}}}}return a};
i2d.pp.mrpcockpit.reuse.util.CalculationEngine.prototype.formatChartDate=function(d){var D=d.toString();if(D==="Invalid Date"){return D}else{return d.toISOString()}};
i2d.pp.mrpcockpit.reuse.util.CalculationEngine.prototype.initialChartData=function(s,d,D,c){var o=new Date(d);var a=new Date(D);a=new Date(a.getTime()+24*3600*1000);var m={shiftLeft:c,decimals:0,startBalance:0,minStock:0,safetyStock:0,minDate:this.formatChartDate(o),maxDate:this.formatChartDate(a),minDateOld:"",maxDateOld:"",oMinDate:o,oMaxDate:a,chartData:[],deltas:[]};var l=(s&&s.length)?s.length:0;var S;var f={};var b="";var e;var M=null;var g=null;var v=0;var h=null;var j=null;var k=null;var n=null;for(var i=0;i<l;i++){S=s[i];v=(i===0)?parseFloat(S.MRPAvailableQuantity):parseFloat(S.MRPElementOpenQuantity);e=S.MRPElementAvailyOrRqmtDate;b=this.formatChartDate(e);if(!g&&S.MRPEvaluationHorizonInDays){var E=parseInt(S.MRPEvaluationHorizonInDays);g=new Date(e.getTime()+E*24*3600*1000)}if(!M||(e<M)){M=e}if(!g||(e>g)){g=e}if(i===0){m.decimals=parseInt(S.TargetQuantityUnitDcmls);m.startBalance=v;m.minStock=parseFloat(S.MaterialShortageThresholdQty);m.safetyStock=parseFloat(S.MaterialShortageCriticalQty)}else{if(!f[b]){f[b]={date:b,demand:0,supply:0,shortageAccepted:S.MRPAvailability===i2d.pp.mrpcockpit.reuse.util.CommonConstants.MRP_AVAILABILITY_ACCEPTED,shortageDefId:S.MaterialShortageDefinitionID}}if(v<0){f[b].demand+=v}else{f[b].supply+=v}}}if(M&&g){var L={shortageAccepted:false,defId:""};for(var e=M;e<=g;e=new Date(e.getTime()+24*3600*1000)){var b=this.formatChartDate(e);if(f[b]){L={shortageAccepted:f[b].shortageAccepted,defId:f[b].shortageDefId};m.chartData.push({date:e,demand:f[b].demand,supply:f[b].supply,shortageAccepted:f[b].shortageAccepted,shortageDefId:f[b].shortageDefId})}else{m.chartData.push({date:e,demand:0,supply:0,shortageAccepted:L.shortageAccepted,shortageDefId:L.defId})}}}return m};
i2d.pp.mrpcockpit.reuse.util.CalculationEngine.prototype.previewChartData=function(c){var d=(c.AvailabilityDate)?c.AvailabilityDate:c.ChangedAvailabilityDate;var D=c.ChangedAvailabilityDate;var s=this.formatChartDate(d);var v=parseFloat(c.MRPElementOpenQuantity);var a=this.formatChartDate(D);var V=parseFloat(c.MRPElementChangeOpenQuantity);var b=[];if(s===a){b=[{date:d,demand:(V<0)?-v+V:0,supply:(V>0)?-v+V:0}]}else{b=[{date:d,demand:(v<0)?-v:0,supply:(v>0)?-v:0},{date:D,demand:(V<0)?V:0,supply:(V>0)?V:0}]}return{oPreviewDate:D,sPreviewDate:a,deltas:b}};
i2d.pp.mrpcockpit.reuse.util.CalculationEngine.prototype.previewChart=function(){};
